### ISSUE TITLE
Unconfirmed transactions in explorer and light clients

### ISSUE THREAD

**Issue by LeeSmet** [rivine/home#10]
When querying an  explorer for an adress, the unconfirmed transactions should be returned too.
This allows a better user experience for people using the web explorer  and makes it easier for light clients, now they have to seperately query the transaction pool which can also cause timing issues.

**Comment by GlenDC** [comment]
Rivine Explorer Feature Request created: rivine/rivine#455

**Comment by robvanmieghem** [comment]
Jumpscale feature : Unconfirmed transactions are not shown in rivine wallet.current_balance https://github.com/threefoldtech/jumpscale_lib/issues/181
