### ISSUE TITLE
milestones not properly set over the account

### ISSUE THREAD

**Issue by despiegk** [rivine/home#3]
please use milestones which correspond with your home page

e.g.

![image](https://user-images.githubusercontent.com/6021844/43352624-91597c46-9226-11e8-9c73-b05ec13cd8f2.png)

there should have been a 1.0.7 
goal is to have over full account only these milestones 1.0.7 - 1.0.8 -  1.1 ... and nothing more

**Comment by GlenDC** [comment]
Didn't know we were still doing the `/home` thing. Now and than I updated it for nostalgic feelings, but thought we had moved away from it, now that we do the story card thing.

Never made the milestones in home repo as we never add issues to the home repo, the tfchain and rivine repos were using the same milestones.

**Comment by GlenDC** [comment]
Can this be closed @robvanmieghem ?
