### ISSUE TITLE
Add the coincreation and minterredefinition to jumpscale 

### ISSUE THREAD

**Issue by robvanmieghem** [rivine/home#7]

**Comment by robvanmieghem** [comment]
requires https://github.com/threefoldtech/jumpscale_lib/issues/79

**Comment by LeeSmet** [comment]
https://github.com/threefoldtech/jumpscale_lib/pull/127

**Comment by LeeSmet** [comment]
I'd say this would require a way to track the minter definition (i.e. request it). Then the jumpscale client can prepare a transaction, which can then be signed (like the current multisig implementation)

**Comment by GlenDC** [comment]
This is already possible, a tfchain daemon exposes this already as a consensus sub endpoint. We could expose it as an explore endpoint as well (basically an alias) so it would become fetcheble from public explorer nodes. See tfchain codebase for more info.

**Comment by LeeSmet** [comment]
Since the caddy config does not proxy the consensus calls, that is indeed what I was suggesting :)

**Comment by GlenDC** [comment]
Makes sense. The current codebase allows the extension of any root endpoint, so should be easy.

**Comment by GlenDC** [comment]
As mentioned previously in chat, the explorer nodes can now also provide this information.

> The `/consensus/mintcondition` and `/consensus/mintcondition/:height` (as well as the corresponding cli `tfchainc consensus mintcondition [height]` command) are still available. But you’ll now also have the `/explorer/mintcondition` and `/explorer/mintcondition/:height` (as well as the corresponding cli `tfchainc explore mintcondition [height]` command)  available to use. The endpoints are basically aliases, the command version ensures it calls always the `/explorer/*` endpoint versions.
